# Generated by Django 3.2.7 on 2021-10-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerText', models.TextField()),
                ('descText', models.TextField()),
                ('bgImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
