# Generated by Django 3.2.7 on 2021-10-25 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_pencari_donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
