# Generated by Django 3.2.7 on 2021-10-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_pencari_donor', '0006_auto_20211029_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='response',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_pencari_report', to='dashboard_pencari_donor.response'),
        ),
    ]
