# Generated by Django 3.2.7 on 2021-10-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_pencari_donor', '0007_alter_report_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='response',
        ),
        migrations.AddField(
            model_name='response',
            name='report',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard_pencari_donor.report'),
            preserve_default=False,
        ),
    ]
