# Generated by Django 3.2.7 on 2021-10-29 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_pencari_donor', '0002_alter_request_pencari_donor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_pencari_donor', '0008_auto_20211029_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_pencari_donor.request_pencari_donor')),
            ],
        ),
    ]
