# Generated by Django 3.2.7 on 2021-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_pencari_donor', '0009_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
