# Generated by Django 3.2.7 on 2021-11-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0011_alter_request_donor_user'),
        ('dashboard_pencari_donor', '0010_donor_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donor_data',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='form_donor.request_donor'),
            preserve_default=False,
        ),
    ]
