# Generated by Django 3.2.7 on 2021-11-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0012_auto_20211105_0940'),
        ('dashboard_pencari_donor', '0012_alter_donor_donor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_donor.request_donor'),
        ),
    ]
