# Generated by Django 3.2.7 on 2021-10-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('kota', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=30)),
                ('jamOperasi', models.CharField(max_length=50)),
                ('kontak', models.CharField(max_length=100)),
            ],
        ),
    ]
