# Generated by Django 3.2.7 on 2021-10-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi_donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utd',
            name='kontak',
        ),
        migrations.AddField(
            model_name='utd',
            name='nomorTelepon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utd',
            name='alamat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='utd',
            name='kota',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utd',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
