# Generated by Django 3.2.7 on 2021-12-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi_donor', '0003_remove_utd_nomortelepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='utd',
            name='nomorTelepon',
            field=models.IntegerField(default=0),
        ),
    ]
