# Generated by Django 3.2.7 on 2021-10-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=12, verbose_name='No. Hp')),
                ('alamat', models.TextField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=9)),
                ('kehamilan', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=False, max_length=5, verbose_name='Apakah Anda pernah atau sedang hamil?')),
                ('usia', models.IntegerField()),
                ('golongan_darah', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('rhesus', models.CharField(choices=[('POSITIVE', '+'), ('NEGATIVE', '-')], max_length=8)),
                ('berat_badan', models.IntegerField()),
                ('gejala_covid', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=None, max_length=5, verbose_name='Apakah Anda memiliki gejala COVID-19 dalam 14 hari terakhir?')),
                ('riwayat_transfusi', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=None, max_length=5, verbose_name='Apakah Anda memiliki riwayat transfusi darah dalam 6 bulan terakhir?')),
                ('penyakit_penyerta', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=None, max_length=5, verbose_name='Apakah Anda memiliki penyakit penyerta (Malaria, Hipertensi, HIV, penyakit jantung, paru-paru, ginjal, dan sebagainya)?')),
                ('positif_covid19', models.DateField(verbose_name='Kapan pertama kali Anda dinyatakan positif COVID-19?')),
                ('file_positif_covid19', models.ImageField(upload_to='uploads/', verbose_name='Upload dokumen hasil pemeriksaan swab PCR positif')),
                ('negatif_covid19', models.DateField(verbose_name='Kapan Anda dinyatakan sembuh dari COVID-19?')),
                ('file_negatif_covid19', models.ImageField(upload_to='uploads/', verbose_name='Upload dokumen hasil pemeriksaan swab PCR negatif atau surat pernyataan telah sembuh minimal selama 14 hari')),
            ],
        ),
    ]
