# Generated by Django 3.2.7 on 2021-10-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendonor',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=9),
        ),
        migrations.AlterField(
            model_name='pendonor',
            name='rhesus',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=8),
        ),
    ]
