# Generated by Django 3.2.7 on 2021-10-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0002_auto_20211025_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendonor',
            name='gejala_covid',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pendonor',
            name='kehamilan',
            field=models.CharField(default='Tidak', max_length=5),
        ),
        migrations.AlterField(
            model_name='pendonor',
            name='penyakit_penyerta',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pendonor',
            name='riwayat_transfusi',
            field=models.CharField(max_length=5),
        ),
    ]
