# Generated by Django 3.2.7 on 2021-10-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0003_auto_20211026_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendonor',
            name='negatif_covid19',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pendonor',
            name='positif_covid19',
            field=models.DateField(),
        ),
    ]
