# Generated by Django 3.2.7 on 2021-10-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0004_auto_20211026_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendonor',
            old_name='negatif_covid19',
            new_name='tanggal_lahir',
        ),
        migrations.RemoveField(
            model_name='pendonor',
            name='file_negatif_covid19',
        ),
        migrations.RemoveField(
            model_name='pendonor',
            name='file_positif_covid19',
        ),
        migrations.RemoveField(
            model_name='pendonor',
            name='gejala_covid',
        ),
        migrations.RemoveField(
            model_name='pendonor',
            name='kehamilan',
        ),
        migrations.RemoveField(
            model_name='pendonor',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='pendonor',
            name='penyakit_penyerta',
        ),
        migrations.RemoveField(
            model_name='pendonor',
            name='positif_covid19',
        ),
        migrations.RemoveField(
            model_name='pendonor',
            name='riwayat_transfusi',
        ),
        migrations.RemoveField(
            model_name='pendonor',
            name='usia',
        ),
        migrations.AddField(
            model_name='pendonor',
            name='komorbid',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pendonor',
            name='nama_lengkap',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pendonor',
            name='nik',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pendonor',
            name='tempat_lahir',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pendonor',
            name='tinggi_badan',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pendonor',
            name='alamat',
            field=models.TextField(default=None),
        ),
    ]
