# Generated by Django 3.2.7 on 2021-10-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0006_auto_20211026_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nik', models.IntegerField()),
                ('no_hp', models.CharField(max_length=12)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=9)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('golongan_darah', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('rhesus', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=8)),
                ('berat_badan', models.IntegerField()),
                ('tinggi_badan', models.IntegerField()),
                ('komorbid', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Pendonor',
        ),
    ]
