# Generated by Django 3.2.7 on 2021-10-26 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form_donor', '0007_auto_20211026_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_donor',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
