# Generated by Django 3.2.7 on 2021-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0009_alter_request_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_donor',
            name='komorbid',
            field=models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=5),
        ),
    ]
