# Generated by Django 3.2.7 on 2021-10-28 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form_donor', '0010_alter_request_donor_komorbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
