# Generated by Django 3.2.7 on 2021-11-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0011_alter_request_donor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_donor',
            old_name='nama_lengkap',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='request_donor',
            old_name='no_hp',
            new_name='nomor_hp',
        ),
        migrations.RenameField(
            model_name='request_donor',
            old_name='nik',
            new_name='nomor_induk',
        ),
    ]
