# Generated by Django 3.2.7 on 2021-11-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_donor', '0012_auto_20211105_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_donor',
            name='nomor_induk',
            field=models.CharField(max_length=16),
        ),
    ]
