# Generated by Django 3.2.7 on 2021-10-27 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='request_pencari_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nomor_induk', models.PositiveIntegerField()),
                ('nomor_hp', models.CharField(max_length=12)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'LAKI-LAKI'), ('Perempuan', 'PEREMPUAN')], max_length=10)),
                ('tempat_lahir', models.CharField(max_length=10)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('golongan_darah', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('rhesus', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=8)),
                ('tempat_rawat', models.TextField()),
                ('urgency', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
