# Generated by Django 3.2.7 on 2021-11-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_pencari_donor', '0002_alter_request_pencari_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_pencari_donor',
            name='nomor_induk',
            field=models.CharField(max_length=16),
        ),
    ]
