# Generated by Django 3.2.7 on 2021-11-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_donor', '0004_auto_20211104_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='status',
        ),
    ]
